# Generated by Django 5.0 on 2023-12-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footballplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('shirtNumber', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
