# Generated by Django 4.1.2 on 2024-02-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footballplayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=200)),
                ('shirtnumber', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
